[package]
name = "co2mini"
version = "0.1.0"
authors = ["Joren Van Onder <joren@jvo.sh>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libusb = "0.3.0"
hidapi = "0.5.2"